---
abstract: 'a perl module interface to WURFL (the Wireless Universal Resource File - L<http://wurfl.sourceforge.net/>).'
author:
  - 'Ave Wrigley <Ave.Wrigley@itn.co.uk>'
  - 'Paul Harvey <csirac2@yahoo.com.au>'
build_requires:
  Benchmark: 0
  DBD::SQLite: 0
  File::Path: 0
  Module::Build: 0.2800
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.2800
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mobile-Wurfl
recommends:
  Git::Repository: 0
requires:
  DBI: 0
  Date::Parse: 0
  File::Basename: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Long: 0
  IO::Uncompress::Gunzip: 0
  IO::Uncompress::Unzip: 0
  LWP::UserAgent: 0
  POSIX: 0
  Pod::Find: 0
  Pod::Usage: 0
  XML::Parser: 0
  lib: 0
  strict: 0
  warnings: 0
version: 2.0
